### ISSUE TITLE
command shopify extension push throwing Tried to load unspecified class: Symbol error

### ISSUE THREAD

**Issue by roxa21** [Shopify/product-reviews-sample-app#17]
When running shopify extension push and any other command except shopify extension create I get the following error:

```
Traceback (most recent call last):
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<main>'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <main>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:17:in `call'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project_type.rb:34:in `load_all'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project_type.rb:34:in `map'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project_type.rb:35:in `block in load_all'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project_type.rb:27:in `load_type'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project_type.rb:27:in `load'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/project_types/extension/cli.rb:3:in `<top (required)>'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/project_types/extension/cli.rb:6:in `<module:Extension>'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/project_types/extension/cli.rb:12:in `<class:Project>'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/project_types/extension/messages/message_loading.rb:7:in `load'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/project_types/extension/messages/message_loading.rb:20:in `load_current_type_messages'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project.rb:171:in `config'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/project.rb:193:in `load_yaml_file'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:586:in `safe_load_file'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:586:in `open'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:587:in `block in safe_load_file'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:334:in `safe_load'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:343:in `each'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:65:in `deserialize'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/scalar_scanner.rb:74:in `tokenize'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:84:in `symbolize'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:32:in `symbolize'
         2: from (eval):2:in `symbol'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:100:in `find': Tried to load unspecified class: Symbol (Psych::DisallowedClass)
```
I'm using cli version 2.3 in a Windows system

Reproduction steps:
1. Run shopify extension create
2. Select app to register with extension
3. Select Theme-app-extension as type of extension
4. After folder is created cd into that folder and run shopify extension push. The above errors occur

**Comment by stevemar** [comment]
Unfortunately I don't have access to a Windows environment to double check this error and dig into it. We've updated the documentation around the theme app extension (https://github.com/Shopify/product-reviews-sample-app/blob/main/docs/theme-app-extension.md) and the entire repo in general. If the behaviour persists please open a new issue.
